## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Configuration for Alacritty, the GPU enhanced terminal emulator.
## It's a very basic and simple config file, for full configuration...
## See, /usr/share/doc/alacritty/example/alacritty.yml

## Import files (Colors, Fonts, Etc)
import:
  - ~/.config/i3/alacritty/colors.yml
  - ~/.config/i3/alacritty/fonts.yml

## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 2
    y: 2

  decorations: full
  startup_mode: Windowed
  dynamic_title: true
  dynamic_padding: false

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
  opacity: 0.93

## Cursor
cursor:
  style: Block
  unfocused_hollow: false
  vi_mode_style: Block
  
font: 
  normal:
    family: JetBrains Mono
    style: Medium
    size: 12
## Live config reload
live_config_reload: true 
