#!/bin/sh
#
# System info

wm="$(wmctrl -m | grep Name: | cut -d ' ' -f2)"
distro="$(cat /etc/*-release | grep PRETTY_NAME | cut -d '=' -f2 | tr -d '"')"
packages="$(pacman -Qq | wc -l)"
ram="$(free -m | awk 'NR==2{printf "%sMB/%sMB\n", $3,$2,$3*100/$2 }')"

printf " \e[0m \n"
printf "   ▄▀ ▄▀ \e[0m \n"
printf "    ▀  ▀    \e[38;5;228m  distro \e[0m$distro\n"
printf "  █▀▀▀▀▀█▄  \e[38;5;228m  pkgs   \e[0m$packages\n"
printf "  █░░░░░█─█ \e[38;5;228m  wm     \e[0m$wm\n"
printf "  ▀▄▄▄▄▄▀▀  \e[38;5;228m  ram    \e[0m$ram\n"

~/scripts/blox
